//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerOrder.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectDB11Entities1 : DbContext
    {
        public ProjectDB11Entities1()
            : base("name=ProjectDB11Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tblcess> tblcess { get; set; }
        public DbSet<tblO> tblO { get; set; }
        public DbSet<tblP> tblP { get; set; }
        public DbSet<tblregister> tblregister { get; set; }
    }
}
