//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerOrder.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcess
    {
        public int ProcessID { get; set; }
        public Nullable<int> Process { get; set; }
    }
}
