//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerOrder.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblP
    {
        public tblP()
        {
            this.tblO = new HashSet<tblO>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<tblO> tblO { get; set; }
    }
}
